### ISSUE TITLE
Trying to get property 'code' of non-object in: thoughtco/kitchendisplay/controllers/Summary.php:268

### ISSUE THREAD

**Issue by BreakSecurity** [ryanmitchell/ti-ext-kitchendisplay#28]
After creating an order without telephone number of customer...
```
ErrorException: Trying to get property 'code' of non-object in /home/info/domains/info.info/public_html/extensions/thoughtco/kitchendisplay/controllers/Summary.php:268
Stack trace:
#0 /home/info/domains/info.info/public_html/extensions/thoughtco/kitchendisplay/controllers/Summary.php(268): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/home/info...', 268, Array)
#1 /home/info/domains/info.info/public_html/storage/framework/views/4246c45a397863067d88ca4e009222ebb561994f.php(51): Thoughtco\KitchenDisplay\Controllers\Summary->renderResults()
```

**Comment by BreakSecurity** [comment]
The order was used with a coupon that made the price be 0 so maybe is due to this

**Comment by ryanmitchell** [comment]
Seems to be version 1?
there is no line 268 in version 2.

**Comment by BreakSecurity** [comment]
Yep totally right I have version 2 in another test env.
